var searchData=
[
  ['highscore_38',['HighScore',['../class_high_score.html',1,'']]],
  ['highscore_2ecs_39',['HighScore.cs',['../_high_score_8cs.html',1,'']]],
  ['highscorebl_2eassemblyinfo_2ecs_40',['HighScoreBL.AssemblyInfo.cs',['../_debug_2net7_80_2_high_score_b_l_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2net7_80_2_high_score_b_l_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['highscorebl_2eglobalusings_2eg_2ecs_41',['HighScoreBL.GlobalUsings.g.cs',['../_debug_2net7_80_2_high_score_b_l_8_global_usings_8g_8cs.html',1,'(Global Namespace)'],['../_release_2net7_80_2_high_score_b_l_8_global_usings_8g_8cs.html',1,'(Global Namespace)']]],
  ['highscoredal_42',['HighScoreDAL',['../namespace_high_score_d_a_l.html',1,'']]],
  ['highscoredal_2eassemblyinfo_2ecs_43',['HighScoreDAL.AssemblyInfo.cs',['../_debug_2net7_80_2_high_score_d_a_l_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2net7_80_2_high_score_d_a_l_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['highscoredal_2eglobalusings_2eg_2ecs_44',['HighScoreDAL.GlobalUsings.g.cs',['../_debug_2net7_80_2_high_score_d_a_l_8_global_usings_8g_8cs.html',1,'(Global Namespace)'],['../_release_2net7_80_2_high_score_d_a_l_8_global_usings_8g_8cs.html',1,'(Global Namespace)']]],
  ['highscoredaltests_45',['HighScoreDALTests',['../namespace_high_score_d_a_l_tests.html',1,'']]],
  ['highscoredaltests_2eassemblyinfo_2ecs_46',['HighScoreDALTests.AssemblyInfo.cs',['../_debug_2net7_80_2_high_score_d_a_l_tests_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2net7_80_2_high_score_d_a_l_tests_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['highscoredaltests_2eglobalusings_2eg_2ecs_47',['HighScoreDALTests.GlobalUsings.g.cs',['../_debug_2net7_80_2_high_score_d_a_l_tests_8_global_usings_8g_8cs.html',1,'(Global Namespace)'],['../_release_2net7_80_2_high_score_d_a_l_tests_8_global_usings_8g_8cs.html',1,'(Global Namespace)']]],
  ['highscoredatabase_48',['HighScoreDataBase',['../class_high_score_data_base.html',1,'']]],
  ['highscoredatabase_2ecs_49',['HighScoreDataBase.cs',['../_high_score_data_base_8cs.html',1,'']]],
  ['highscoredatacsv_50',['HighScoreDataCSV',['../class_high_score_data_c_s_v.html',1,'']]],
  ['highscoredatacsv_2ecs_51',['HighScoreDataCSV.cs',['../_high_score_data_c_s_v_8cs.html',1,'']]],
  ['highscoredatacsvtests_2ecs_52',['HighScoreDataCSVTests.cs',['../_high_score_data_c_s_v_tests_8cs.html',1,'']]],
  ['highscoredatajson_53',['HighScoreDataJSON',['../class_high_score_data_j_s_o_n.html',1,'']]],
  ['highscoredatajson_2ecs_54',['HighScoreDataJSON.cs',['../_high_score_data_j_s_o_n_8cs.html',1,'']]],
  ['highscoredatajsontests_2ecs_55',['HighScoreDataJSONTests.cs',['../_high_score_data_j_s_o_n_tests_8cs.html',1,'']]],
  ['highscoredataxml_56',['HighScoreDataXML',['../class_high_score_data_x_m_l.html',1,'']]],
  ['highscoredataxml_2ecs_57',['HighScoreDataXML.cs',['../_high_score_data_x_m_l_8cs.html',1,'']]],
  ['highscoredataxmltests_2ecs_58',['HighScoreDataXMLTests.cs',['../_high_score_data_x_m_l_tests_8cs.html',1,'']]],
  ['highscoremodels_2eassemblyinfo_2ecs_59',['HighScoreModels.AssemblyInfo.cs',['../_debug_2net7_80_2_high_score_models_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2net7_80_2_high_score_models_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['highscoremodels_2eglobalusings_2eg_2ecs_60',['HighScoreModels.GlobalUsings.g.cs',['../_debug_2net7_80_2_high_score_models_8_global_usings_8g_8cs.html',1,'(Global Namespace)'],['../_release_2net7_80_2_high_score_models_8_global_usings_8g_8cs.html',1,'(Global Namespace)']]],
  ['highscorerepository_61',['HighScoreRepository',['../class_high_score_repository.html',1,'HighScoreRepository'],['../class_high_score_repository.html#aa808c2976cb1899c16e7eb1d895e6635',1,'HighScoreRepository.HighScoreRepository()']]],
  ['highscorerepository_2ecs_62',['HighScoreRepository.cs',['../_high_score_repository_8cs.html',1,'']]],
  ['highscores_63',['HighScores',['../class_high_score_data_base.html#a26ba0bb86aa9ca377f9b5a859adb04c8',1,'HighScoreDataBase.HighScores()'],['../class_data_transfer_object.html#a6c317ce7c21537202f47207671c329a5',1,'DataTransferObject.HighScores()'],['../interface_high_score_d_a_l_1_1_utils_1_1_i_high_score_data_base.html#ab1584b391fc125b39ad814c9c83b21f9',1,'HighScoreDAL.Utils.IHighScoreDataBase.HighScores()']]],
  ['highscoresrepo_64',['HighScoresRepo',['../class_unit_of_work.html#ae347e1c1bf30065870378c730f7d995a',1,'UnitOfWork']]],
  ['utils_65',['Utils',['../namespace_high_score_d_a_l_1_1_utils.html',1,'HighScoreDAL']]]
];
